# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f32c57d1de9113d888b6c2e7db8e8318"
name = "primox-app"
handle = "vienna-roast"
application_url = "https://finds-numerical-injury-sheffield.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = ["https://finds-numerical-injury-sheffield.trycloudflare.com/auth/callback", "https://finds-numerical-injury-sheffield.trycloudflare.com/auth/shopify/callback", "https://finds-numerical-injury-sheffield.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
